version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Map host's port 8080 to the frontend service's port 8080
    environment:
      - NODE_ENV=production
      - PORT=8080
    networks:
      - my_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8081:8080"  # Map host's port 8081 to the backend service's port 8080
    environment:
      - NODE_ENV=production
      - PORT=8080
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
